### ISSUE TITLE
Relationship empty

### ISSUE THREAD

**Issue by JeanetteMueller** [Sorix/CloudCore#10]
i try to add an entity to my coredata. it has an relationship to-many to another entity. but on this place i just want to add the first entity. now i have an empty list of relationships. 
so i get error: 
`SaveToCloudDidFailed: <CKError 0x1c4a49300: "Invalid Arguments" (12/2006); server message = "cannot use an empty list to initialize a new field (field 'episodes' in record type 'ManagedPodcast' should be more precise)";`

i tried to add an dummy object to start with no empty list but then i got another error:
`SaveToCloudDidFailed: <CKError 0x1c045a4f0: "Invalid Arguments" (12/1007); "Invalid list of records: Cycle detected in record graph">`

**Comment by Sorix** [comment]
I think I fixed that error, you may check it in `1.0.1` version.
