### ISSUE TITLE
Doesn't fetch

### ISSUE THREAD

**Issue by cristibaluta** [Sorix/CloudCore#14]
Hi,
I implemented this lib and i noticed this behaviour:
1. every time I change a coredata object it uploads to cloudkit only those changes into a new record
2. reinstalling the app from scratch does not get the records from ck

Am I missing something or the lib is not doing what is supposed to do?

**Comment by cristibaluta** [comment]
Made more tests and the fetch works but saving doesn't, i had to hack and use directly the main context. After that it still doesn't work properly, every change from ck creates a new entry in the db that will get uploaded to ck in the end

**Comment by Sorix** [comment]
@ralcr, please check v2 branch (#13), v1 has a lot of issues. I will merge it soon to master branch.

**Comment by cristibaluta** [comment]
Thanks, not sure there's an issue with the lib after all, for some reason NSFetchedResultsController cannot see the records created by cloudcore but it sees the ones created by me. Doing a normal fetch sees them all.
