### ISSUE TITLE
Both app and Xcode crashes after saving to Core Data

### ISSUE THREAD

**Issue by brightfuture** [Sorix/CloudCore#18]
Awesome project Sorix, can't say how much I appreciate this 😍

But I ran into a tricky bug, which I hardly know what happened due to Xcode crashes with my app when the bug triggers. 

I've tried to comment out any coding using CloudCore, the app runs fine, so the problem must comes from CloudCore;
And I put breakpoints in `willSave` and `didSave` in `CoreDataListener`, when this code is executed slow, interestingly my app did not crash, I wasn't able to locate the problem either;
The bug doesn't trigger every time I save to Core Data, if I create a new object to save, all is well; If I modify the value of an existing object and then save, boom! It crashes; 

That's all I observed, I'll keep digging into the problem.

**Comment by brightfuture** [comment]
An update on this problem:

This crash seem to be caused by concurrency problem when interacting with core data, Cloud Core uses a background queue to perform operations writing to core data, while my app uses the main queue, I changed this line in `main` function in `ObjectToRecordOperation.swift`:

    let childContext = NSManagedObjectContext(concurrencyType: .privateQueueConcurrencyType)

to 

    let childContext = NSManagedObjectContext(concurrencyType: .mainQueueConcurrencyType)

and the crash disappeared. 

This is probably a suboptimal solution, I'll work on some better solutions in the future.

**Comment by Sorix** [comment]
It's a very strange, I will investigate that issue, because it's a major one if it is true, thank you.

**Comment by brightfuture** [comment]
This problem seems to be cause by a bug of mine, it's just not exposed to me before I used CloudCore. 

Too bad Xcode just crashes every time instead of telling me where went wrong. 

Now I can properly sync with Xcode without changing one line of code in this framework.

**Comment by tkhelm** [comment]
I was experiencing a crashing bug that sounds very similar. I updated Xcode to v9.3-beta and it no longer occurs in the app I am building. Same good result with the current beta 2.
