### ISSUE TITLE
I have a crash in CloudCoreConfig.swift

### ISSUE THREAD

**Issue by AL-maher** [Sorix/CloudCore#22]
Hi,,
I have a crash when running the application with the following code in class CloudCoreConfig.swift:

`    /// Default value is `CKContainer.default()`
	// `lazy` is set to eliminate crashes during unit-tests
    public lazy var container = CKContainer.default()`

Is there a solution to this problem?

**Comment by Sorix** [comment]
Please provide more information about crash (screenshots / logs).
