### ISSUE TITLE
Changes not synced

### ISSUE THREAD

**Issue by theslash** [Sorix/CloudCore#29]
Hi,
I just test the framework in a simple app with a tableview.
when I add a entry on one device, the other device gets the change notification and when I reload the tableview the new entry is there, same with deletions.
but when I edit an entry the changeNotification comes, but I only see the change after killing and restarting the app. can someone give me a hint what I'm doing wrong?

**Comment by theslash** [comment]
I found out this in the Cloud Dashboard:
when I call CloudCore.fetchAndSave i see "operation: zone changes database:" in Cloud Dashboard Log.
when I kill the App and start i also see "operation: subscription fetch database:"  being called before, and I see the changes

**Comment by theslash** [comment]
Ok I figured it out:
I had to do reset before reloading my core Data:

`      CloudCore.fetchAndSave(to: persistenceService.persistentContainer, error: { (error) in
            print("FetchAndSave error: \(error)")
            DispatchQueue.main.async {
                persistenceService.context.reset()
                self.getCoreData()
            }
        }) {
            DispatchQueue.main.async {
                persistenceService.context.reset()
                self.getCoreData()
            }
        }`

**Comment by lukepistrol** [comment]
@theslash thanks for sharing!! I had the exact same issue… And now thanks to you it works 😊
