### ISSUE TITLE
How to sync transformable type ?

### ISSUE THREAD

**Issue by parth1009** [Sorix/CloudCore#32]
Hello.

I have one transformable type of attribute in my core data table for UIImage. Is it possible to sync transformable type ?

Thanks

**Comment by Scytalion** [comment]
Hi parth1009,
if you save your image as "Binary Data" sync should work right away. If you need to save it as a transformable: I have created a pull request for support of transformable (NSCoding) attributes.

**Comment by parth1009** [comment]
Thanks Scytalion.
It is working fine with "Binary Data". One more question is there.
How do I remove that synced data from iCloud ?

**Comment by Sorix** [comment]
> How do I remove that synced data from iCloud ?

I'm working on it, I will add that method soon. Also I have to add that method because of new EU policy. Anyway it is feature request, so I'm closing that ticket for now, thank you for idea.

**Comment by parth1009** [comment]
Okay.
Thanks for your support man. You can close the previous one.
