### ISSUE TITLE
Merge Conflicts

### ISSUE THREAD

**Issue by theslash** [Sorix/CloudCore#37]
Sorry for perhaps asking stupid questions, but I'm pulling my hair here and can't get
it to work properly.
I have a simple Application with a tableView that is filled with coreData.
Just one entity called "Person", no relationships, 4 attributes: name, age, recordData, recordID.

I have pulled the CoreData functions in a separate class called persistenceService.
In my AppDelegate I enabled CloudCore like this:

        CloudCore.enable(persistentContainer: persistenceService.persistentContainer)

In my viewcontroller I have two functions I use for this:

#1: Fetch CoreData and reload Tableview
```swift
    func getCoreData() {
        //      get data from coredata
        let fetchRequest: NSFetchRequest<Person> = Person.fetchRequest()
        let sortDescriptor = NSSortDescriptor(key: "recordID", ascending: true)
        fetchRequest.sortDescriptors = [sortDescriptor]
     
        do {
            self.people = try persistenceService.context.fetch(fetchRequest)
        } catch {}
        self.tableView.reloadData()
    }
```
    
    
#2 Fetch Cloud Data 
```swift
    func fetchCloudData() {
        print("fetchAndSave and Reloading Tableview")
        CloudCore.fetchAndSave(to: persistenceService.persistentContainer, error: { (error) in
            print("FetchAndSave error: \(error)")
        }) {
            DispatchQueue.main.async {
                persistenceService.context.reset()
                self.getCoreData()
            }
        }
    }
```
    
What works:
I create a new entry, it gets synced to iCloud.
I delete a record in iCloud, call fetchCloudData() and its gone.
I edit a record, call fetchCloudData() and its edited in local storage.

BUT all this only works when I call persistenceService.context.reset() in the fetchCloudData()
function.

Lets say I start the app, CloudCore syncs, and then I try to edit/delete an entry I always get 
an error like this:

```
["conflictList": <__NSArrayM 0x600000648df0>(
NSMergeConflict (0x60000086fd80) for NSManagedObject (0x604000294a00) with objectID '0xd000000000580000 <x-coredata://BB8BBB3E-0F70-4ED2-BDCD-D15AB86480B0/Person/p22>' with oldVersion = 7 and newVersion = 8 and old object snapshot

```
When I start the app and once call the fetchCloudData() function, it works, when I
uncomment the persistenceService.context.reset() part it gets the same error as above.

can someone please hint me what I'm doing wrong?

**Comment by Sorix** [comment]
> I edit a record, call fetchCloudData() and its edited in local storage.

What record (`CKRecord`?) do you edit if you deleted it at step 2?

**Comment by theslash** [comment]
I get the record from the tableview and delete like this:
the error occurs while saving.

people is defined in the viewcontroller like this:
`var people = [Person]()`

```swift
 func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
       
        **let itemToDelete = people[indexPath.row]**
        print(itemToDelete)
        
        if (editingStyle == UITableViewCellEditingStyle.delete) {

            **persistenceService.context.delete(itemToDelete)**
            self.people.remove(at: indexPath.row)
            
            do {
                try persistenceService.context.save()
            } catch let error as NSError {
                print("Error While Deleting: \(error.userInfo)")
            }
        }
        getCoreData()        
    }
```

Here the output as example: 
the print(itemToDelete):

```
<Person: 0x600000291c60> (entity: Person; id: 0xd000000000580000 <x-coredata://BB8BBB3E-0F70-4ED2-BDCD-D15AB86480B0/Person/p22> ; data: {
    age = 2222;
    name = blub44;
    recordData = <62706c69 73743030 d4010203 04050640 41582476 65727369 6f6e5824 6f626a65 63747359 24617263 68697665 72542474 6f70>;
    recordID = "815B15CF-E203-4BFA-B827-0BA8BB0CBA9F|__defaultOwner__";
})
```

And here the error:

```
Error While Deleting: ["conflictList": <__NSArrayM 0x60000044f150>(
NSMergeConflict (0x600000678380) for NSManagedObject (0x600000291c60) with objectID '0xd000000000580000 <x-coredata://BB8BBB3E-0F70-4ED2-BDCD-D15AB86480B0/Person/p22>' with oldVersion = 8 and newVersion = 9 and old object snapshot = {
    age = 2222;
    name = blub44;
    recordData = ...
    recordID = "815B15CF-E203-4BFA-B827-0BA8BB0CBA9F|__defaultOwner__";
} and new cached row = {
    age = 2222;
    name = blub44;
    recordData = ...
    recordID = "815B15CF-E203-4BFA-B827-0BA8BB0CBA9F|__defaultOwner__";
}
)
]
```

I removed the recordData to make it better readable

**Comment by Sorix** [comment]
Could you give your example application, so I won't need to create new one for that ticket?

**Comment by theslash** [comment]
sure, thank you very much, I uploaded the project here:
https://github.com/theslash/test_cloudCore

I deactivated my team, and the iCloud switch before saving

**Comment by Sorix** [comment]
I've commented `persistenceService.context.reset()`
1. I've create a new record in application.
2. I deleted it.

I see no errors. I missed something in reproduction?

**Comment by theslash** [comment]
Yes. Ist Happens when you:
Create a record, kill The App, Start it again.

Then Just try to delete/edit a record. 
Then it should fail.

**Comment by theslash** [comment]
Does anyone have an idea what I can do?

**Comment by theslash** [comment]
I think I understand the problem:
When I start the app, the fetchAndSave Func runs. 
But it runs just after the viewDidLoad where the coreDataObject is fetched.

I tested it with a new project, I have a list of objects, start the app, the fetchRequest runs, then the fetchAndSave function runs.
When I then try to delete or edit a coreData object I get the merge error.

can someone point me out what I'm doing wrong?

**Comment by theslash** [comment]
Ok, solved:

I added a mergePolicy in the CoreData Class:

        container.viewContext.mergePolicy = NSMergeByPropertyObjectTrumpMergePolicy
