### ISSUE TITLE
Multiple devices syncing across CloudKit

### ISSUE THREAD

**Issue by magnas35** [Sorix/CloudCore#4]
I can put the demo app onto a phone and an iPad and see the additions syncing across to the other app but deletions only seem to work one way, from one device to the other but not from the second. Am I expecting the wrong behavior?

**Comment by Sorix** [comment]
It is wrong behaviours, I will check it on that week, all syncs are two-way.

**Comment by Sorix** [comment]
@magnas35 sorry for late answer, I've checked, everything is working okay. Do you tested on real devices or used emulators (for both devices)? If you're using emulator you need to push on _refresh_ button (push notifications doesn't work on emulators) to fetch updated data.

**Comment by magnas35** [comment]
Yes, I was testing on two real devices, an iPhone and an iPad. I will retest.

**Comment by Sorix** [comment]
@magnas35 I will double check in 3-4 hours that in every situation it is working, thank you for providing information that it were 2 real devices.
