### ISSUE TITLE
Bug for fetchAndSave on RecordToCoreDataOperation

### ISSUE THREAD

**Issue by EvgeniyBruchkovskiy** [Sorix/CloudCore#7]
<img width="841" alt="2017-09-04 10 59 04" src="https://user-images.githubusercontent.com/25980666/30017000-1e94c430-9160-11e7-9274-8e2876c75d17.png">
I have a 2 Entity's 
<img width="793" alt="2017-09-04 11 00 41" src="https://user-images.githubusercontent.com/25980666/30017062-531c1582-9160-11e7-8a6f-15d88eff23eb.png">
The client is stored normally. Only client, doesn't DateOfRecords.
When I save DateOfRecords and fetch or save in cloudKit come about crash. 

Please, help me for my question.

P.S. Sorry for my English.

**Comment by Sorix** [comment]
Any way to provide source code if it is not private to test it? You can send it to [my mail](http://www.google.com/recaptcha/mailhide/d?k=01eFEpy-HM-qd0Vf6QGABTjw==&c=JrKKY2bjm0Bp58w7zTvPiQ==) with steps to reproduce.

**Comment by EvgeniyBruchkovskiy** [comment]
Сan show in skype, record from the screen

2017-09-12 23:16 GMT+03:00 Vasily Ulianov <notifications@github.com>:

**Comment by Sorix** [comment]
I've checked my code, I can't find some lines in method that had thrown an error in my files. Maybe you're using a fork or some outdated version?

Current version of that method is:
```swift
/// Fill provided `NSManagedObject` with data
///
/// - Parameters:
///   - entityName: entity name of `object`
///   - recordDataAttributeName: attribute name containing recordData
private func fill(object: NSManagedObject, entityName: String, serviceAttributeNames: ServiceAttributeNames, context: NSManagedObjectContext) throws {
	for key in record.allKeys() {
		if self.isCancelled { return }
		
		let recordValue = record.value(forKey: key)
		
		let attribute = CloudKitAttribute(value: recordValue, entityName: entityName, serviceAttributes: serviceAttributeNames, context: context)
		let coreDataValue = try attribute.makeCoreDataValue()
		object.setValue(coreDataValue, forKey: key)
	}
	
	// Set system headers
	object.setValue(record.recordID.encodedString, forKey: serviceAttributeNames.recordID)
	object.setValue(record.encdodedSystemFields, forKey: serviceAttributeNames.recordData)
}
```

There is no `is [Any]`.
