### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by JeanetteMueller** [Sorix/CloudCore#9]
is it possible to start a progress to migrate existing data to cloudcore?
at the moment the recordData field is empty. The recordID Field is an already as GUID used field.

**Comment by Sorix** [comment]
Don't write any data manually to `recordData` and `recordID`, that attributes are managed by CloudCore.

I will add in next version force uploading all data (even not changed) from current database to CloudKit, that is easy task, but I need some time. I will post here when it will be completed.

**Comment by Sorix** [comment]
Will be fixed in [version 2](https://github.com/Sorix/CloudCore/tree/v2) soon, zone creating/recreating/purging/syncing will be managed automatically.
